### ISSUE TITLE
ReScript

### ISSUE THREAD

**Issue by mellson** [tmattio/js-bindings#3]
Is it possible to make the bindings compatible with ReScript?

**Comment by tmattio** [comment]
Hi @mellson

The bindings use `gen_js_api.1.0.8` and I don't think it is compatible with ReScript.
In addition, the ppx uses `ppxlib`. I didn't follow the recent advancement of ReScript closely, but I think it introduced a breaking change that makes the compiler incompatible with `ppxlib`, so I don't think there's any chance for the bindings to be compatible with ReScript in the future either.

**Comment by mellson** [comment]
@tmattio thanks for the detailed answer! I'm still to new to ReScript to understand it all and be helpful. So I'm closing the issue now but hopefully I can help out in the future.
